### ISSUE TITLE
Future plans

### ISSUE THREAD

**Issue by alokraj68** [ryanvolum/offline_dl#14]
Hey!
This is an awesome project.
I would like to know how you're planning the future of this project?
Especially the attachment support and https support.

**Comment by ryanvolum** [comment]
Cheers, and thanks!

I'll be honest, I built this as a quick fix to a problem I saw lots of developers having. I don't have the bandwidth to make have feature-parity with the Bot Framework Connector. That said, I'm more than happy to field PRs from the community! 

Another thing I'll note is that the next generation of the botbuilder SDK will allow you to host your bot code in the browser, without a connector at all. Of course, this doesn't help for channel bots (bots on facebook messenger, skype, teams, slack, etc), but dramatically simplifies the developer experience for bots in the browser.

**Comment by ryanvolum** [comment]
FYI, I just opened up issue #15 to request help on the attachment front. The https support is a harder problem, but a solveable one as well.

**Comment by alokraj68** [comment]
Dear Ryan,
Thanks a lot for replying. We were going through the new things in Bf. We did not want to pay for Directline since we are making an open source product. We thought we will have the power to decide where we should host it and also, decide if we need premium things like Directline. We are ready to host our own DL. Since you said about the new implementation,

Can we know more about that? 
Is there any timeline when we can use it like the same way it is now.

**Comment by ryanvolum** [comment]
Here's the v4 SDK, which can run a bot in browser: https://github.com/Microsoft/botbuilder-js

I don't think it has a sample for this capability yet, but it should be coming!
