### ISSUE TITLE
Get Conversation ID from URL

### ISSUE THREAD

**Issue by howlowck** [ryanvolum/offline_dl#17]
## Issue:
When doing a post to send a message to the bot, the conversation ID is not set properly.  The conversation ID is set using a global scope, instead from the URL.

https://github.com/ryanvolum/offline_dl/blob/master/src/bridge.ts#L72

## Proposal:
Add an optional `conversationId` parameter in `createMessageActivity` signature. If it's not defined, it defaults to the global variable.

https://github.com/ryanvolum/offline_dl/blob/master/src/bridge.ts#L216

-----------
I can make a PR if this sounds good.

**Comment by ryanvolum** [comment]
Hey Hao - this sounds good - feel free to make the PR!

**Comment by howlowck** [comment]
Awesome! PR submitted 😄
