### ISSUE TITLE
Is directline port fixed at 3000? How to send messages to two bot services?

### ISSUE THREAD

**Issue by shadabtamboli** [ryanvolum/offline_dl#23]
I have two bot endpoints. Iam able to communicate with them from bot client but only one at a time. 

I need to setup two bot clients which will talk to different directline ports. How can I host directline on on different port and communicate with two endpoints? 

 Also I am not able to host directlline on any other port other than 3000.

**Comment by ryanvolum** [comment]
@shadabtamboli, thanks for the request. In 1.2.4 I've updated the ```initializeRoutes``` function to take an optional port number, which will default to 3000. This should resolve your issue!

```export const initializeRoutes = (app: express.Server, serviceUrl: string, botUrl: string, conversationInitRequired = true, port: number = 3000) ```

**Comment by mattmazzola** [comment]
Does this mean the port given in `serviceUrl` must match the value of port variable?  I'm not sure how it works when these are different.

E.g.
```
serviceUrl: http://127.0.0.1:3000
port: 3000
```

My understanding was `seviceUrl` was supposed to be the base url for the direct offline instance that is created.  It just happened to work because the port was defaulted to 3000

**Comment by shadabtamboli** [comment]
It works only with port 3000. However you can go to js and replace 3000
with code to extract port number from base url.

**Comment by mattmazzola** [comment]
> It works only with port 3000
No, I ended up testing it.  It works on other ports. It's just that the serviceUrl should be constructed using the port you pass in.
There are parts within the implementation of API that use the serviceUrl in responses so it needs this data, but in most cases it could have been constructed from the port as you see in this file:

https://github.com/ryanvolum/offline_dl/blob/961d129c1f68540d01232b3fe08a7469a1959d77/src/cmdutil.ts#L9

```typescript
const port = 4366
const serviceUrl = `http://127.0.0.${port}`
directline.initializeRoutes(app, serviceUrl, botEndpoint, port)
```

**Comment by ryanvolum** [comment]
@shadabtamboli matt is right here. You can optionally pass whatever port you like as your last parameter. This wasn't initially the case, so it seems a bit redundant now to declare your service url (with your port) _and_ your port. A minimal refactor here would reduce confusion - will throw it on the backlog.
