### ISSUE TITLE
Is there any docs about Websocket?

### ISSUE THREAD

**Issue by pavei** [ryanvolum/offline_dl#26]
Hi, 

I want to develop WS protocol with directline. Is there any docs that i can use to develop this?

**Comment by ryanvolum** [comment]
hey @pavei. Though this project is emulating the bot framework connector it was never my intention to have feature parity with the connector. The[ bot framework emulator](https://github.com/Microsoft/BotFramework-Emulator) _also_ emulates the connector and I believe it does implement websockets. Though not the most satisfying answer, you might dig through their source code for inspiration

**Comment by pratiksinghchauhan** [comment]
Hey @pavei, I had the same requirement, so if you wish we can collaborate for this project. Please reply if interested.

**Comment by pavei** [comment]
Yep! 

I did some code.. and i got how to do this. I did too reconnecting with conversation, using a local database.  I could share it, but i dont know if @ryanvolum will accept my pull request.. hehehehe 

I think we maybe  fork this project..

**Comment by pratiksinghchauhan** [comment]
sure can you share your hangouts, facebook or anything we could talk on there, I would have mailed you but your profile does not have a mail id?

**Comment by pavei** [comment]
My facebook is Vinicius Zilli Pavei or my skype vinicius.pavei :)  





On Sat, Jul 21, 2018 3:37 PM, Pratik Singh Chauhan notifications@github.com 
wrote:
sure can you share your hangouts, facebook or anything we could talk on there, I
would have mailed you but your profile does not have a mail id?
