### ISSUE TITLE
bot response issue

### ISSUE THREAD

**Issue by ppandura** [ryanvolum/offline_dl#32]
getting the same response as what we send due to the check history, suggest to add for  router.get('/directline/conversations/:conversationId/activities', (req, res) => { after Line#57}

if(activities[0].replyToId) {
                    res.status(200).json({
                        activities,
                        watermark: watermark + activities.length
                    });
                }
                else {
                    res.status(200).send({
                        activities: [],
                        watermark: watermark + activities.length
                    });
                }

**Comment by ryanvolum** [comment]
Hey @ppandura I'm not sure I understand the exact issue. This repo is meant to be used as a jumping off point, and it sounds like you were able to update your code to get it working the way you expected!
