### ISSUE TITLE
Parameter "url" must be a string, not undefined

### ISSUE THREAD

**Issue by shafi-mohammed** [ryanvolum/offline_dl#33]
Hi @ryanvolum,

I'm getting this error when i run app.js:
Created conversation with conversationId: a7d5c610-141f-43ea-b2c9-3b3edab4da8a
(node:23484) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 34): TypeError: Parameter "url" must be a string, not undefined

Do you have any idea about this issue?

Appreciate your help.

Thanks,
Shaf

**Comment by sschutten** [comment]
I assume you're setting up offline-directline in code. Did you follow the steps outlined in the readme? Make sure that the second URL in this line points to your bot:
`directline.initializeRoutes(app, "http://127.0.0.1:3000", "http://127.0.0.1:3978/api/messages");`

**Comment by ryanvolum** [comment]
@shafi-mohammed I'm not able to repro - did you follow @sschutten's directions? Please reopen if you keep seeing issues...
