### ISSUE TITLE
CORS header allow x-ms-bot-agent

### ISSUE THREAD

**Issue by AGeekDad** [ryanvolum/offline_dl#37]
Getting error:
`CORS policy: Request header field x-ms-bot-agent is not allowed by Access-Control-Allow-Headers in preflight response.`

directline.js is now sending `x-ms-bot-agent` in commonHeaders method:
https://github.com/Microsoft/BotFramework-DirectLineJS/blob/master/src/directLine.ts

Need to add this header to `Access-Control-Allow-Headers`:
        res.header('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept, Authorization, x-ms-bot-agent');

**Comment by schemburkar** [comment]
i too am seeing this exact issue. Can we get this merged sooner?

**Comment by ryanvolum** [comment]
Apologies @schemburkar and @AGeekDad - I haven't been monitoring this repo. I'll take a look at the PR today and cut a new package if it looks good! Thanks for the contribution :)

**Comment by ryanvolum** [comment]
This has been resolved with #38
