### ISSUE TITLE
send conversation update to bot

### ISSUE THREAD

**Issue by Timothee-Retailleau** [ryanvolum/offline_dl#8]
Hello,

I'm working with a bot that does need to send proactive message when the conversation starts.

This do not work currently, I'm working to solve it by adding a fetch in "app.post/directline/conversation" with an activity type "members added".

would be great to have all the conversation updates to be send to the bot.

**Comment by ryanvolum** [comment]
Hey @Timothee-Retailleau, apologies for the gratuitously late response. I built this project as a quick fix, and haven't had the time to follow the issues. Your solution sounds like it likely resolves the issue, I'd be happy to review a pull request and make it part of the solution.

**Comment by ryanvolum** [comment]
The latest build (1.2.3) now has conversation updates!
