### ISSUE TITLE
OPTIONS `/directline/conversations/:conversationId` not found

### ISSUE THREAD

**Issue by chiayenhung** [ryanvolum/offline_dl#9]
When I went through the examples in the README.
First two requests get success.
1. OPTIONS `/directline/conversations`
2. POST `/directline/conversations`

But the sub-sequential calls OPTIONS `/directline/conversations/:conversationId` getting 404 not found

**Comment by ryanvolum** [comment]
There's no endpoint for OPTIONS on that uri. What examples in what README are you talking about?

**Comment by ryanvolum** [comment]
If you take a look at bridge.ts, you can see all of the API routes that are implemented. All routes that the bot connector uses are at least stubbed out - those which aren't implemented have log a console.warn.

**Comment by ryanvolum** [comment]
I think I better understand your problem @chiayenhung and believe it's the same issue as [issue #2 ](https://github.com/ryanvolum/offline_dl/issues/2)

**Comment by alexknipfer** [comment]
@chiayenhung Did you ever find a solution to this, currently dealing with the same?
